#!/usr/bin/env bash
set -euo pipefail
# A BTN field runs a command without closing the form, allowing click readback.
if [[ "${1:-}" == --clicked ]]; then
  printf 'clicked\n' >"$2/clicked"
  exit
fi
RUN="$1"
HERE="$(cd "$(dirname "$0")" && pwd)"
# Private-session GTK settings only: stable glyphs and no blinking/animation.
mkdir -p "$XDG_CONFIG_HOME/gtk-3.0"
printf '[Settings]\ngtk-font-name=Monospace 12\ngtk-cursor-blink=false\ngtk-enable-animations=false\n' >"$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
# Paths are generated by this harness; quoting also permits a checkout with spaces.
exec yad --title='Native restoration fixture' --form --width=480 --height=180 \
  --no-buttons --field='Restoration entry' 'before restoration' \
  --field='Prove click:BTN' "bash '$HERE/fixture.sh' --clicked '$RUN'"
